---
version: '2.2'

networks:
  default:
    external:
      name: sodas

services:
  sodas.gs.zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: sodas.gs.zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  sodas.gs.broker:
    image: confluentinc/cp-kafka
    container_name: sodas.gs.broker
    depends_on:
      - sodas.gs.zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: sodas.gs.zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sodas.gs.broker:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_EXTERNAL_PORT: 9094